name: "Validate Gradle Wrapper"
on: [push, pull_request, workflow_dispatch]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses:  gradle/actions/wrapper-validation@v4
